name: servers_cobaltax
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - paramiko
  - pip:
    - requests
    - ping3
    - telethon
    - python-telegram-bot
    - pyvmomi
    - cryptography
    - fastapi
    - "uvicorn[standard]"
    - python-multipart
    - ldap3
